export const TORONTO_WARDS = [
    { id: "1", name: "Etobicoke North" },
    { id: "2", name: "Etobicoke Centre" },
    { id: "3", name: "Etobicoke—Lakeshore" },
    { id: "4", name: "Parkdale—High Park" },
    { id: "5", name: "York South—Weston" },
    { id: "6", name: "York Centre" },
    { id: "7", name: "Humber River—Black Creek" },
    { id: "8", name: "Eglinton—Lawrence" },
    { id: "9", name: "Davenport" },
    { id: "10", name: "Spadina—Fort York" },
    { id: "11", name: "University—Rosedale" },
    { id: "12", name: "Toronto—St. Paul's" },
    { id: "13", name: "Toronto Centre" },
    { id: "14", name: "Toronto—Danforth" },
    { id: "15", name: "Don Valley West" },
    { id: "16", name: "Don Valley East" },
    { id: "17", name: "Don Valley North" },
    { id: "18", name: "Willowdale" },
    { id: "19", name: "Beaches—East York" },
    { id: "20", name: "Scarborough Southwest" },
    { id: "21", name: "Scarborough Centre" },
    { id: "22", name: "Scarborough—Agincourt" },
    { id: "23", name: "Scarborough North" },
    { id: "24", name: "Scarborough—Guildwood" },
    { id: "25", name: "Scarborough—Rouge Park" }
];
