import React from 'react';
import { ExternalLink, CalendarDays, Vote } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageMeta } from '../PageMeta';
import { CivicCard, CivicSectionLabel } from '../ui/CivicCard';

const OFFICIAL = 'https://vancouver.ca/your-government/2026-election.aspx';

export default function VancouverElection() {
    return <div className="max-w-5xl mx-auto space-y-8 pb-20"><PageMeta title="2026 Vancouver Election | Motions" description="Official voting information and Vancouver council voting records for the 2026 municipal election." /><div><CivicSectionLabel>2026 VANCOUVER ELECTION</CivicSectionLabel><h1 className="text-3xl sm:text-4xl font-bold text-slate-900 mt-1">Know the council record before you vote.</h1><p className="text-slate-500 mt-3 max-w-2xl">Vancouver elects its mayor and 10 councillors citywide. Candidate information is published by the City after nominations close.</p></div><div className="grid gap-4 sm:grid-cols-2"><CivicCard><CalendarDays className="w-5 h-5 text-[#004a99]" /><CivicSectionLabel>KEY DATES</CivicSectionLabel><div className="space-y-3 text-sm text-slate-700"><Row date="September 1–11" label="Nomination period" /><Row date="September 8" label="Vote-by-mail applications open" /><Row date="October 3, 7, 10, 13" label="Advance voting" /><Row date="October 17" label="Election day" /></div></CivicCard><CivicCard><Vote className="w-5 h-5 text-[#004a99]" /><CivicSectionLabel>THE BALLOT</CivicSectionLabel><ul className="space-y-2 text-sm text-slate-600"><li>1 mayor</li><li>10 city councillors</li><li>7 Park Board commissioners</li><li>9 school trustees</li><li>Capital Plan and plebiscite questions</li></ul></CivicCard></div><CivicCard><CivicSectionLabel>CANDIDATES</CivicSectionLabel><h2 className="text-lg font-semibold text-slate-900 mt-1">Candidate list pending final nominations</h2><p className="text-sm text-slate-500 mt-2">The official nomination period closes September 11. Once the City publishes the certified list, Motions will add mayor and councillor candidate profiles here.</p><a href="https://vancouver.ca/your-government/run-for-office-in-vancouver.aspx" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-sm font-semibold text-[#004a99] mt-4">Official candidate information <ExternalLink className="w-3.5 h-3.5" /></a></CivicCard><div className="flex flex-wrap gap-3"><Link to="/councillors" className="rounded-xl bg-slate-900 text-white px-4 py-2.5 text-sm font-semibold">Review council records</Link><a href={OFFICIAL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Official election site <ExternalLink className="w-4 h-4" /></a></div></div>;
}

function Row({ date, label }) { return <div className="flex gap-3"><span className="font-semibold text-slate-900 min-w-[116px]">{date}</span><span>{label}</span></div>; }
