import fs from 'node:fs';

const path = 'public/data/vancouver/motions.json';

// Explicit title-by-title decisions made against docs/CATEGORIZATION_GUIDE.md.
// This map records decisions already made by a human review; it is not a
// classifier. Identical amendment/roll-call titles receive the same decision.
const decisions = new Map([
  ['Applications to Government of British Columbia Funding Programs', 'Finance'],
  ['Accessibility Audit of all City-Owned Assets', 'Governance'],
  ['Approval of Council Initiatives â€“ Business Improvement Area (BIA) Renewals 2023\nNovember 1, 2022', 'Finance'],
  ['2022 Cultural Grants (Equity, Indigenous, Artists, Spaces)', 'Parks'],
  ['Vancouver Civic Theatres Rental Rates 2023-2024', 'Parks'],
  ['2023 Engineering Fees', 'Finance'],
  ['2023 Annual Review of Water Rates and Water Works By-law Amendments', 'Climate'],
  ['2023 Land Assessment Averaging: Notice to BC Assessment Authority', 'Finance'],
  ['Miscellaneous Changes to the Building Board of Appeal By-law', 'Governance'],
  ['Miscellaneous Amendments Concerning Various CD-1 By-laws', 'Planning & Development'],
  ['2022 Community Services and Other Social Grants', 'Finance'],
  ['- 2023 Street Cleaning Grants', 'Finance'],
  ['- Alignment with the Electrical Safety Regulations, Housekeeping, and Miscellaneous Updates to the Building and Electrical By-laws', 'Planning & Development'],
  ['- Establishment of Civic Agencies', 'Governance'],
  ['Equity Lens Review of City By-laws to Ensure Equity is at the Forefront', 'Governance'],
  ['CD-1 Text Amendment: 319-359 West 49th Avenue (319 West 49th Avenue)', 'Planning & Development'],
  ['2023 Report #2 - Office Furniture Purchases', 'Finance'],
  ['Approval of Business Improvement Area (BIA) Renewals 2023', 'Finance'],
  ['Local Improvement - Approval of Billing Rates for Projects Completed in 2022', 'Finance'],
  ['2023 Property Taxation: Development Potential Relief and Targeted Land Assessment Averaging', 'Finance'],
  ['Regulating the Sale of Bear Spray', 'Public Safety'],
  ['Vancouver Community Sport Event Grants - Spring 2023 Intake', 'Parks'],
  ['Annual Federation of Canadian Municipalities (FCM), Union of British Columbia Municipalities (UBCM), and Lower Mainland Local Government Association (LMLGA) Membership Fees for 2023 to 2024', 'Finance'],
  ['Approval of 2023-24 Business Improvement Area (BIA) Budgets', 'Finance'],
  ['Broadway Plan Implementation', 'Planning & Development'],
  ['Water Works By-law Exemptions and/or Viable Exceptions for Notable Decorative City Water Features (Motion B.2)', 'Climate'],
  ['Water Works By-law Exemptions and/or Viable Exceptions for Notable Decorative City Water Features', 'Climate'],
  ['By-Law 2 - A By-law to amend License By-law No. 4450 regarding the sale of bear spray - Amendment', 'Public Safety'],
  ['By-Law 2 - A By-law to amend License By-law No. 4450 regarding the sale of bear spray - By-law as Amended', 'Public Safety'],
  ['2023 Cultural Grants (Balance of Operating Grants)', 'Parks'],
  ['New Leases for Eight Child Care Centres and Two Family Place Drop-in Centres', 'General'],
  ['Accessibility Strategy Implementation Update and Council Motion Report Back', 'Governance'],
  ['Protecting People on Cornwall Avenue (Members\' Motion B3)', 'Public Safety'],
  ['2023 Property Taxation: Rating By-laws and Averaging Resolutions', 'Finance'],
  ['2023 Cultural Grants (CASC, Cultural Spaces)', 'Parks'],
  ['Water Works & Drinking Water Conservation By-law Amendments', 'Climate'],
  ['Proposed Fire By-law Amendments for Notice Delivery', 'Public Safety'],
  ['The Permitting Program Cost Recovery Model Transmittal Report', 'Finance'],
  ['Plumbing and Administrative Amendments to the Vancouver Building By-law, Water Works By-law and By-law Notice Enforcement By-law', 'Planning & Development'],
  ['Vancouver Community Sport Event Grants - Summer 2023 Intake', 'Parks'],
  ['Allocation of Additional 2023 Plaza and Parklet Street Cleaning Grants', 'Finance'],
  ['2023 UBCM Resolutions', 'Governance'],
  ['2023 Annual Inflationary Rate Adjustment to Development Cost Levies', 'Finance'],
  ['Green Infrastructure Pre-Qualification of Landscape and Civil Contractors - Adopted on Consent', 'Climate'],
  ['Creating Safer Streets for People of All Ages with Intersection Safety Cameras', 'Public Safety'],
  ['Building Safer Communities Program - Youth Safety and Violence Prevention Strategy', 'Public Safety'],
  ['Commercial Vehicle Permit Program Improvements', 'Transit'],
  ['Lease Extension with Covenant House Vancouver for 326 West Pender Street', 'Housing'],
  ['2024 Engineering Fees', 'Finance'],
  ['2024 Annual Review of Water Rates and Water Works By-law Amendments', 'Climate'],
  ['2024 Land Assessment Averaging: Notice to BC Assessment Authority', 'Finance'],
  ['Plumbing, Sprinkler and Mechanical Updates to the Building By-law', 'Planning & Development'],
  ['2024 Community Services and Other Social Grants - Final Motion A and L', 'Finance'],
  ['2024 Community Services and Other Social Grants - FINAL MOTION B to K and M to S', 'Finance'],
  ['Vancouver Community Sport Event Grants - Spring 2024 Intake', 'Parks'],
  ['2024-25 Business Improvement Area (BIA) Budgets', 'Finance'],
  ['Expanding Free Public WiFi in the Downtown Eastside and Adjacent Neighbourhoods', 'General'],
  ['2024 Property Taxation: Pilot Development Potential Relief Program and Targeted Land Assessment Averaging', 'Finance'],
  ['2024 Cultural Grants (Balance of Operating, Capacity)', 'Parks'],
  ['Single-Use Item By-laws and Report Back on Cup Policies', 'Climate'],
  ['Alcohol on Beaches - 2024 Re-Pilot - Motion 1', 'Parks'],
  ['Alcohol on Beaches - 2024 Re-Pilot - Motion 2', 'Parks'],
  ['Enabling Third-Party Investment in EV Charging Infrastructure on City Streets', 'Climate'],
  ['Updating Efficiency Standards for Water Heaters in Existing Detached Homes', 'Climate'],
  ['Improving the Effectiveness of the Standards of Maintenance (SOM) By-law', 'Planning & Development'],
  ['Establishing a Chinatown Cultural District', 'Parks'],
  ['Closing the Gap: Investing in the City of Vancouver\'s Food System to Increase Food Access and Support a Resilient, Equitable, and Sustainable Food', 'Climate'],
  ['Expanding the School Travel Planning Program', 'Transit'],
  ['2025 Engineering Fees', 'Finance'],
  ['2025 Annual Review of Water Rates and Water Works By-law Amendments', 'Climate'],
  ['2025 Land Assessment Averaging: Notice to BC Assessment Authority', 'Finance'],
  ['2025 Cultural Grants (Projects, Advance, Multiyear, Cultural Spaces)', 'Parks'],
  ['Effective Water Use in the City of Vancouver', 'Climate'],
  ['Key Directions for the Healthy Waters Plan', 'Climate'],
  ['Childcare Strategy Implementation and Policy Harmonization', 'General'],
  ['2025 Community Services & Other Social Grants', 'Finance'],
  ['Amendment to Licence By-Law - SRA Vacancy Control', 'Housing'],
  ['2025 Community Sport Event Grants â€“ Spring 2025 Intake', 'Parks'],
  ['2025 Cultural Grants (Balance of Operating, Capacity)', 'Parks'],
  ['Reducing Home Demolition Waste in Vancouver', 'Climate'],
  ['2025 Homelessness Services Grants', 'Housing'],
  ['Supervised Indoor Inhalation Spaces', 'Public Safety'],
  ['New Edition of the Fire By-law (2025 Fire By-law)', 'Public Safety'],
  ['2025 Community Services, Childcare & Other Grants', 'Finance'],
  ['2025 Graffiti Abatement Grants for Business Improvement Areas', 'Finance'],
  ['A Drain on Resources and Resources Down the Drain: Pulling the Plug on In-Sink Garbage Disposal', 'Climate'],
  ['Opening Doors: Expanding Ownership Options for Laneway and Backyard Homes', 'Housing'],
  ['Prohibiting the Sale of Gun-shaped Lighters (GSL)', 'Public Safety'],
  ['Request for Review of School Liaison Officer Program', 'Public Safety'],
  ['2026 Annual Review of Water Rates and Water Works By-law Amendments', 'Climate'],
  ['2026 Engineering Fees - Amendment to E', 'Finance'],
  ['2026 Engineering Fees - Amendment to K', 'Finance'],
  ['2026 Engineering Fees - Amendment to B', 'Finance'],
  ['2026 Engineering Fees - Final Motion B', 'Finance'],
  ['2026 Engineering Fees - Final Motion C', 'Finance'],
  ['2026 Engineering Fees - Final Motion - A, and D through K', 'Finance'],
  ['Report 5. 2025 Community Services and Other Grants', 'Finance'],
  ['Report 6. Business Improvement Areas (BIA) Renewals 2026', 'Finance'],
  ['2025 Cultural Grants (Equity, Indigenous, Redress, Spaces, Public Art)', 'Parks'],
  ['Cultural Tourism and Community Sport Hosting Grants 2025 Year End', 'Parks'],
  ['Vancouver Civic Theatres Rental Rates 2026-2027', 'Parks'],
  ['Declaration of Dangerous Building at 341 East Hastings Street, Vancouver', 'Public Safety'],
  ['Washroom Strategic Framework and 2026 Actions', 'General'],
  ['Tools for Tenancies: Closing the Gap by Enforcing Accountability and Adding Conditions to Licensing Landlords in the City of Vancouver', 'Housing'],
  ['2026 Cultural Grants (Balance of Operating, Cultural Spaces) - Amendment', 'Parks'],
  ['2026 Cultural Grants (Balance of Operating, Cultural Spaces)', 'Parks'],
  ['Vancouver Community Sport Event Grants - Spring 2026 Intake', 'Parks'],
  ['Business License Hearing Panels â€“ November and December 2022', 'Governance'],
  ['Update on the Development of a Sewage and Rainwater Management Plan', 'Climate'],
  ['2023 Report #1 - Building Permit Fees', 'Finance'],
  ['Business Licence Cancellation (STR) - 1397 West 41st Avenue', 'Housing'],
  ['Closure and Sale of a Portion of Lane Adjacent to 150 West Pender Street', 'Planning & Development'],
  ['Harmonizing City of Vancouver and Provincial Childcare Policies and Licensing Requirements - Amendment to the Amendment', 'General'],
  ['Harmonizing City of Vancouver and Provincial Childcare Policies and Licensing Requirements - Amendment', 'General'],
  ['Harmonizing City of Vancouver and Provincial Childcare Policies and Licensing Requirements - Sections A and D', 'General'],
  ['Harmonizing City of Vancouver and Provincial Childcare Policies and Licensing Requirements - Sections B and C', 'General'],
  ['Industrial Modernization and Intensification Framework Development Process Update (Member Motion B.3)', 'Planning & Development'],
  ['2023 Report #1 - Building Permit Fees', 'Finance'],
  ['2023 UBCM Resolutions', 'Governance'],
  ['Commemorating the Komagata Maru Incident: Secondary Naming of a Street', 'Governance'],
  ['FCM Resolution for Submission: Building an Advocacy Case to Increase Government of Canada Support for Literacy Programs', 'Governance'],
  ['Approval of Below-Market Licenses for Zero Waste Demonstration Site Pilot at City Owned Property 1198 East Kent Avenue South', 'Climate'],
  ['Authorization to Negotiate a Development Agreement and Ground Lease with Fraser Academy Association at 2294 West 10th Avenue', 'Planning & Development'],
  ['Funding Approval and Legal Agreement Authorization for Cedar Cottage Neighbourhood House Redevelopment', 'Planning & Development'],
  ['A.8 UBCM Resolution: A New Fiscal Framework for Sustainable and Predictable Local Government Funding', 'Finance'],
  ['A.5 UBCM Resolution: Tackling BC\'s Toxic Drug Health Emergency', 'Public Safety'],
  ['A.6 UBCM Resolution: Decreasing Food Waste, Increasing Food Security', 'Climate'],
  ['Amendments to the Mayor and Councillor Expenses By-law', 'Governance'],
  ['Public Notice By-law', 'Governance'],
  ['Clarifications of Construction and Project Values in the Building By-law', 'Planning & Development'],
  ['Accessibility Committee: Designation and Remuneration - amendment to the amendment', 'Governance'],
  ['Accessibility Committee: Designation and Remuneration - amended amendment', 'Governance'],
  ['Accessibility Committee: Designation and Remuneration - amended motion', 'Governance'],
  ['Recommended 2023 Grants to Support Childcare, Indigenous Healing and WellnessSpace Renovations, Intergenerational Mentorship Programming, and DTES', 'Finance'],
  ['Provincial Funding Request - Access to Washrooms and Water in Vancouver', 'General'],
  ['2024 Community Sport Event Grants â€“ Fall 2023 Intake - Adopted on Consent', 'Parks'],
  ['Trans, Gender Diverse and Two-Spirit (TGD2S) Inclusion and Safety Action Plan', 'Public Safety'],
  ['Regularizing Road Paint Maintenance for Safety', 'Transit'],
  ['2024 Community Services and Other Social Grants', 'Finance'],
  ['2024 Cultural Grants (Projects, Advance, Multiyear)', 'Parks'],
  ['Single-Use Item By-laws and Report Back on Cup Policies - Amendment', 'Climate'],
  ['Single-Use Item By-laws and Report Back on Cup Policies - Amendment to the Amendment', 'Climate'],
  ['Single-Use Item By-laws and Report Back on Cup Policies - Amendment as Amended', 'Climate'],
  ['Single-Use Item By-laws and Report Back on Cup Policies', 'Climate'],
  ['Arbutus Greenway - Establishment of City Land for Street and Public Space Purposes - Amendment', 'Transit'],
  ['Arbutus Greenway - Establishment of City Land for Street and Public Space Purposes - Motion as Amended', 'Transit'],
  ['Enabling Third-Party Investment in EV Charging Infrastructure on City Streets', 'Climate'],
  ['Updating Efficiency Standards for Water Heaters in Existing Detached Homes', 'Climate'],
  ['Allowing Gas Heating and Hot Water in New Construction', 'Climate'],
  ['Sustainable School Food Funding - Amendment', 'Climate'],
  ['Sustainable School Food Funding', 'Climate'],
  ['2025 Annual Review of Water Rates and Water Works By-law Amendments', 'Climate'],
  ['Potential to Update the Vancouver Building Bylaw to Enable Single Egress Stairs', 'Planning & Development'],
  ['Potential to Update the Vancouver Building Bylaw to Enable Single Egress Stairs Low & Mid-Rise Buildings to Align with Provincial Changes to the B', 'Planning & Development'],
  ['Strata Title Conversion of 4288 Yew Street - Amendment', 'Planning & Development'],
  ['Strata Title Conversion of 4288 Yew Street', 'Planning & Development'],
  ['Hotel Development Policy Update - Amendments A to E proposed', 'Planning & Development'],
  ['Hotel Development Policy Update - Amendment add E', 'Planning & Development'],
  ['Hotel Development Policy Update - Final Motion A', 'Planning & Development'],
  ['Hotel Development Policy Update - Final Motion C(b)', 'Planning & Development'],
  ['Hotel Development Policy Update - Final B, the remaining clause of C, and D to F', 'Planning & Development'],
  ['Reducing Home Demolition Waste in Vancouver', 'Climate'],
  ['Supervised Indoor Inhalation Spaces', 'Public Safety'],
  ['New Edition of the Fire By-law (2025 Fire By-law)', 'Public Safety'],
  ['2025 Community Services, Childcare & Other Grants', 'Finance'],
  ['2025 Graffiti Abatement Grants for Business Improvement Areas', 'Finance'],
  ['Opening Doors: Expanding Ownership Options for Laneway and Backyard Homes', 'Housing'],
  ['City-Wide Design and Development Guidelines â€“ Phase Two Actions - amendment', 'Planning & Development'],
  ['City-Wide Design and Development Guidelines â€“ Phase Two Actions - final motion as amended', 'Planning & Development'],
  ['Prioritizing Accessibility and Public Participation at City Council', 'Governance'],
  ['Proposed Changes to the Terms of Reference of the Accessibility Committee', 'Governance'],
  ['Report 1. Operator Appointment for Little Mountain Neighbourhood House and Childcare', 'Governance'],
  ['Report 8. New St. Paul\'s Hospital and Health Campus - Road Establishments', 'Planning & Development'],
  ['National Child and Youth Mental Health Day Actions', 'Public Safety'],
  ['CD-1 (730) Amendment: 6428-6438 Cambie Street and 480-488 West 48th Avenue (Formerly 478-496 West 48th Avenue)', 'Planning & Development'],
  ['Closure and Sale of a Portion of Road Adjacent to 2235 Charles Street', 'Planning & Development'],
  ['Tools for Tenancies: Closing the Gap by Enforcing Accountability and Adding Conditions to Licensing Landlords in the City of Vancouver', 'Housing'],
  ['Abandoned and Vacated Buildings By-law (AVBB)', 'Planning & Development'],
  ['Report Back - Potential to Update the Vancouver Building By-law to Enable Single Egress Stairs', 'Planning & Development'],
  ['A World Cup for Everyone: Exploring Free Public Viewing Opportunities at BC Place and the PNE Amphitheatre', 'Parks'],
  ['Igniting our Spirits: Bringing Vancouver Together Through Summer Celebration', 'Parks'],
  ['Advancing Democratic Innovation in Vancouver Municipal Elections to Increase Voter Turnout and Improve Democratic Legitimacy', 'Governance'],
  ['Audit of Land Sales and Exchanges', 'Finance'],
  ['2025 Annual Whistleblower Report', 'Governance'],
  ['By-law Amendments to Encourage Electric Vehicle (EV) Charging at Gas Stations and Parking Lots', 'Climate'],
  ['Cheap, Easy and Everywhere: Unlocking the full potential of shared mobility to reduce', 'Transit'],
  ['Extended Hours for Liquor Establishments and Restaurants During the 2022 FIFA World Cup', 'General'],
  ['Business Licence Hearing Panels â€“ September to December 2023', 'Governance'],
  ['Business Licence Hearing Panels - January to July 2024', 'Governance'],
  ['Business Licence Hearing Panels - September to December 2024 - Adopted on Consent', 'Governance'],
  ['Business Licence Hearing Panels - January to July 2025', 'Governance'],
  ['Assignment of Business Licence Hearing Panels for September to December 2025 and changes to Business Licence Hearing Panels for May - July 2025', 'Governance'],
  ['Business Licence Hearing Panel Assignments - January to September 2026', 'Governance'],
  ['2024 Report #2: Audit of Childcare, Cultural and Social Non-Profit Leases', 'Governance'],
  ['Fire By-law Amendments for Fire Protection Upgrades', 'Public Safety'],
  ['Installing Means Prevention Fencing on the Granville Street Bridge', 'Public Safety'],
  ['Zero Waste 2040 5-Year Implementation Update', 'Climate'],
  ['Arbutus Greenway - Establishment of City Land for Street and Public Space Purposes - Amendment', 'Transit'],
  ['Arbutus Greenway - Establishment of City Land for Street and Public Space Purposes - Motion as Amended', 'Transit'],
  ['2025 Street Cleaning Grant Program', 'Finance'],
  ['2024 Street Cleaning Grant Program', 'Finance'],
  ['Contract Award for Security Services', 'Public Safety'],
  ['Transport Pricing - \'Stopping the Road Tax\' (Member\' Motion B.6)', 'Transit'],
  ['Contract Award for the Supply and Delivery of Large Fire Apparatus', 'Public Safety'],
  ['Improving Life Safety in SROs: Updates and Grant to SRO-Collaborative - Amendment', 'Housing'],
  ['Improving Life Safety in SROs: Updates & Grant to SRO-Collaborative - Amendment to the Amendment', 'Housing'],
  ['Improving Life Safety in SROs: Updates & Grant to SRO-Collaborative - Amendment as Amended', 'Housing'],
  ['Improving Life Safety in SROs: Updates & Grant to SRO-Collaborative', 'Housing'],
  ['- Grant to VCH for expanded Mental Health Response', 'Public Safety'],
  ['Repealing Vancouver\'s Single-Use Beverage Cup Fee - Amendment add as 2nd Clause', 'Climate'],
  ['Repealing Vancouver\'s Single-Use Beverage Cup Fee - Amendment to add to end of 2nd clause', 'Climate'],
  ['Repealing Vancouver\'s Single-Use Beverage Cup Fee - Amendment to 1st Clause', 'Climate'],
  ['Repealing Vancouver\'s Single-Use Beverage Cup Fee - Amendment to 2nd Clause', 'Climate'],
  ['Repealing VancouverIs Single-Use Beverage Cup Fee - Final Motion Clause 1', 'Climate'],
  ['Repealing Vancouver\'s Single-Use Beverage Cup Fee - Final Motion Clause 2', 'Climate'],
  ['Repealing Vancouver\'s Single-Use Beverage Cup Fee - Final Motion Clause 3', 'Climate'],
  ['Repealing Vancouver\'s Single-Use Beverage Cup Fee - Amendment Whereas Clause 12', 'Climate'],
  ['Contract Award for Prequalified Contractors for Landfill Gasworks Program', 'Climate'],
  ['Contract Award for Consultant for Landfill Design and Contract Administration - Phase 5 Closure', 'Climate'],
  ['2023 Animal Welfare Grant', 'Public Safety'],
  ['2024 Animal Welfare Grant', 'Public Safety'],
  ['2025 Animal Welfare Grant', 'Public Safety'],
  ['Contract Award for Supply of Used Mattress Recycling Services', 'Climate'],
  ['Contract Award for Green Bin Organics Processing', 'Climate'],
  ['Contract Award for Aerial Fire Apparatus', 'Public Safety'],
  ['Contract Award for Supply and Delivery of Aerial Fire Apparatus', 'Public Safety'],
  ['Urgent Mental Health and Substance Use Service Enhancements Grant', 'Public Safety'],
  ['2024 Homelessness Services Grants and Heat Preparedness Response Program Grant', 'Housing'],
  ['2025 Homelessness Services Grants', 'Housing'],
  ['2026 Supplemental Street Cleaning Grant (DTES - Project Hope)', 'Finance'],
  ['Contract Award for Operator for Kitsilano Beach Restaurant', 'Parks'],
  ['Contract Award for Tree Related Maintenance Services Pre-Qualification', 'Parks'],
  ['Contract Award for Supply of Contracted Janitorial Services', 'General'],
  ['Contract Award for Provision of City Fleet Electric Vehicle Charging Infrastructure', 'Climate'],
  ['Contract Award for Construction Services - Arbutus Greenway and West 41st Avenue Intersection Improvements', 'Transit'],
  ['Vancouver Technical Secondary School Synthetic Turf Field â€“ Construction Licence Agreement and Custody, Care, and Management of Land', 'Parks'],
  ['Vancouver Technical Secondary School Synthetic Turf Joint Use Agreement', 'Parks'],
  ['Kitsilano Secondary Synthetic Turf Replacement and Sport Field Lighting â€“ Licence Agreements, Custody, Care, Management of Land and Expenditure of Development Cost Levies', 'Parks'],
  ['Report 7. Vancouver Technical Secondary School Synthetic Turf Joint Use Agreement', 'Parks'],
  ['2024 Budget Adjustment related to risk mitigation of the Hemlock Looper Moth in Stanley Park', 'Parks'],
  ['2024 Draft Operating and Capital Budget - Add M (re: libraries)', 'Parks'],
  ['Contract Award for Food and Beverage Broadline Distributor for the Vancouver Board of Parks and Recreation', 'Parks'],
  ['Contract Award for a Food and Beverage Broadline Distributor for the Vancouver Board of Parks and Recreation', 'Parks'],
  ['Stanley Park Train Accessibility', 'Parks'],
  ['Stanley Park Train Accessibility - Amendment', 'Parks'],
  ['Contract Award for Construction Services for Killarney Park Track and Field Civil Works', 'Parks'],
  ['Capital Budget Adjustment - New Park at Main and 7th Avenue', 'Parks'],
  ['Contract Award for Service Provider to Assist the City in the Planning and Delivery of the FIFA Fan Festival T', 'Parks'],
  ['Member Motion 1. Support for Japanese Canadian Interpretive Centre at Hastings Park', 'Parks'],
  ['2024 Climate Budget', 'Climate'],
  ['Proposed Amendment to Sewer and Watercourse By-law No. 8093', 'Climate'],
  ['Reducing Average Sewer Upgrade Costs for Developers', 'Climate'],
  ['Contract Award for Supply of Water Meter Assemblies', 'Climate'],
  ['Contract Award for Supply and Delivery of Water Meter Assemblies', 'Climate'],
  ['Contract Award for Provision of Advanced Water Metering Infrastructure', 'Climate'],
  ['Funding Application to Local Government Development Approvals Program', 'Planning & Development'],
  ['Development Approval Procedure By-law', 'Planning & Development'],
  ['City of Vancouver Official Development Plan', 'Planning & Development'],
  ['Granville Street Plan - motion as amended', 'Planning & Development'],
  ['Modernizing Business Licence Land Uses and Policies - Amendments to the Zoning and Development By-law, Downtown ODP By-law and Licence By-law', 'Planning & Development'],
  ['Modernizing Business Licence Land Uses and Policies - Amendments to the Zoning and Development By-law, Downtown Official Development Plan By-law an', 'Planning & Development'],
  ['Request for Review of School Liaison Officer Program - amendment', 'Public Safety'],
  ['Request for Review of School Liaison Officer Program - amendment to the amendment', 'Public Safety'],
  ['2STGD+ Safety and Inclusion Action Plan Renewal', 'Public Safety'],
  ['Report 1. FIFA World Cup 2026 By-law', 'Governance'],
  ['FIFA World Cup 26 Vancouver Special Use Lane Designation', 'Transit'],
  ['Recommitting to $10 a Day Childcare', 'General'],
  ['Recommitting to $10 a Day Childcare - Amendment to Strike and Replace', 'General'],
  ['Council Resolution - Supervised Consumption Spaces - Amendment to the Amendment', 'Public Safety'],
  ['Authorization to Negotiate a Development Agreement and Ground Lease with Fraser Academy Association at 2294 West 10th Avenue', 'Planning & Development'],
  ["Provincial 'Growing Communities Fund': Initial Allocation to City Projects - Final Motion part C", 'Finance'],
  ["Provincial 'Growing Communities Fund': Initial Allocation to City Projects - amendment three subsection i", 'Finance'],
  ["Provincial 'Growing Communities Fund': Initial Allocation to City Projects - Final Motion parts A,B,D,Dii", 'Finance'],
  ['Closure of a Portion of Road Adjacent to 181 West Georgia Street', 'Planning & Development'],
  ['Closure and Sale of a Portion of Lane Adjacent to 5025 Arbutus Street, 2126 West 34th Avenue and 2109-2129 West 35th Avenue - Final Vote', 'Planning & Development'],
  ['Resolution - Closure and Sale of a Portion of Lane Adjacent to 5025 Arbutus Street, 2126 West 34th Avenue and 2109-2129 West 35th Avenue', 'Planning & Development'],
  ['Below Market Lease and Grant to Helen\'s Court Co-op at 2137 West 1st Avenue - Adopted on Consent', 'Housing'],
  ['Enhancing Public Safety through Real-Time Access to the City\'s Traffic Camera Network', 'Public Safety'],
  ['Enhancing Public Safety through Real-Time Access to the Cityâ€™s Traffic Camera Network', 'Public Safety'],
  ['Report 1. Broadway Plan Review and Implementation', 'Planning & Development'],
  ['New Edition of the Building By-law (2025 VBBL)', 'Planning & Development'],
  ['Housekeeping and Miscellaneous Changes to the Building By-law', 'Planning & Development'],
  ['2026 Land Assessment Averaging: Notice to BC Assessment Authority', 'Finance'],
  ['CD-1 (818) Text Amendment: 120-150 West Georgia Street, 720-770 Beatty Street and 701 Expo Boulevard (Formerly 720-770 Beatty Street and 701 Expo Boulevard)', 'Planning & Development'],
  ['CD-1 (843) Text Amendment: 888 West Broadway (Formerly 878-898 West Broadway) - Adopted on Consent', 'Planning & Development'],
  ['CD-1 (409) Text Amendment: 1109-1139 West Pender Street and 1122-1152 West Hastings Street (Formerly 1128 West Hastings Street) - Adopted on Consent', 'Planning & Development'],
  ['CD-1 (887) Text Amendment: 625-777 Pacific Street and 1390 Granville Street (Granville Loops) (Text Amendment Impacts 675 Pacific Street and 1395 Rolston Street Only)', 'Planning & Development'],
  ['Enabling Mass Timber Construction Beyond 12 Storeys', 'Planning & Development'],
  ['Enabling Mass Timber Construction Beyond 12 Storeys - Amendment', 'Planning & Development'],
  ['Expanding the School Travel Planning Program - Motion as Amended', 'Transit'],
  ['Expanding the School Travel Planning Program - Second Clause of Amendment', 'Transit'],
  ['Expanding the School Travel Planning Program - Amendment', 'Transit'],
  ['Citywide Development Guidelines Early Actions - Public Views, Solar Access, and Residential Tower Floorplates', 'Planning & Development'],
  ['City-Wide Design and Development Guidelines - Phase Two Actions - referral motion', 'Planning & Development'],
  ['City-Wide Design and Development Guidelines - Phase Two Actions - amendment', 'Planning & Development'],
  ['Reviewing Council\'s Committees & Structure to Enhance Decision-Making Processes', 'Governance'],
  ['2024 Cultural Grants (Equity, Indigenous, Individual Artists, Capacity)', 'Parks'],
  ['2025 Cultural Grants (Projects, Capacity, Cultural Spaces)', 'Parks'],
  ['2025 Cultural Grants (Projects, Advance, Multiyear, Cultural Spaces)', 'Parks'],
  ['Chinatown Strategic Priority Grants', 'Finance'],
  ['Contract Award for Supply of Tree Related Maintenance Services Pre-Qualification', 'Parks'],
  ['Overholding Agreement and Grant to Creekview Co-op at 1483 Lameys Mill Road Recommendations', 'Housing'],
  ['Demolition Permitting Optimization', 'Planning & Development'],
  ['Supporting Local Businesses: A Proactive Approach to Retail Security', 'Public Safety'],
  ['Walking the Talk: Aligning City Staff\'s and Council\'s Remote Work Policy', 'Governance'],
  ['Walking the Talk: Aligning City Staff\'s and Council\'s Remote Work Policy - Amendment to B and C', 'Governance'],
  ['Change Order for Consulting Services for the Healthy Waters Plan', 'Climate'],
  ['Contract Award for Construction Services for Marpole Community Centre Construction Project', 'Parks'],
  ['Contract Award for Marpole Community Centre Construction Project', 'Parks'],
  ['CD-1 (818) Text Amendment: 120-150 West Georgia Street, 720-770 Beatty Street and 701 Expo Boulevard (Formerly 720-770 Beatty Street and 701 Expo Boulevard)', 'Planning & Development'],
  ["Provincial 'Growing Communities Fund': Initial Allocation to City Projects - Final Motion part C", 'Finance'],
  ["Provincial 'Growing Communities Fund': Initial Allocation to City Projects - Final Motion section Dii", 'Finance'],
  ["Provincial 'Growing Communities Fund': Initial Allocation to City Projects - Final Motion parts A,B,D,Dii", 'Finance'],
  ['CD-1 (843) Text Amendment: 888 West Broadway (Formerly 878-898 West Broadway)', 'Planning & Development'],
  ['CD-1 (843) Text Amendment: 888 West Broadway (Formerly 878-898 West Broadway) - Adopted on Consent', 'Planning & Development'],
  ['CD-1 (887) Text Amendment: 625-777 Pacific Street and 1390 Granville Street (Granville Loops) (Text Amendment Impacts 675 Pacific Street and 1395 Rolston Street Only)', 'Planning & Development'],
  ['CD-1 (899) Text Amendment: 3360-3384 Vanness Avenue and 3347 Clive Avenue - Adopted on Consent', 'Planning & Development'],
  ['CD-1 (839) Text Amendment: 5590 Victoria Drive and 2005 East 40th Avenue', 'Planning & Development'],
  ['(887) Text Amendment: 675 Pacific Street', 'Planning & Development'],
  ['(50) Text Amendment: 3282-3296 East 1st Avenue', 'Planning & Development'],
  ['CD-1 (50) Text Amendment: 3282-3296 East 1st Avenue', 'Planning & Development'],
  ['CD-1 (198) Text Amendment: 1700-1750 West 75th Avenue', 'Planning & Development'],
  ['Closure and Sale of a Portion of Lane Adjacent to 716 West 23rd Avenue', 'Planning & Development'],
  ['Closure of a Portion of Road Adjacent 525 Powell Street', 'Planning & Development'],
  ['UB 1. Resolution â€“ Closure of a Portion of Road Adjacent 525 Powell Street', 'Planning & Development'],
  ['Closure and Sale of a Portion of Lane Adjacent to 2096 West Broadway and 2560 Arbutus Street - Adopted on Consent', 'Planning & Development'],
  ['2026 Land Assessment Averaging: Notice to BC Assessment Authority', 'Finance'],
  ['2025 Land Assessment Averaging: Notice to BC Assessment Authority', 'Finance'],
  ['2024 Land Assessment Averaging: Notice to BC Assessment Authority', 'Finance'],
  ['2023 Land Assessment Averaging: Notice to BC Assessment Authority', 'Finance'],
  ['CD-1 (836) Text Amendment: 1075 Nelson Street (Formerly 1059-1083 Nelson Street)', 'Planning & Development'],
  ['(519) Text Amendment and Gaming Control Act Approval: 39-65 Smithe Street - Amendment', 'Planning & Development'],
  ['(899) Text Amendment: 3360-3384 Vanness Avenue and 3347 Clive Avenue', 'Planning & Development'],
  ['2023 Cultural Grants (Equity, Indigenous, Artists)', 'Parks'],
  ['2024 Cultural Grants (Equity, Indigenous, Individual Artists, Capacity)', 'Parks'],
  ['2025 Cultural Grants (Projects, Capacity, Cultural Spaces)', 'Parks'],
  ['Prioritization Framework for Planning Policy and Processing Applications', 'Planning & Development'],
  ['Pilot Development Potential Relief Program - Stakeholder Feedback & Considerations for 2024', 'Finance'],
  ['Supporting Local Businesses: A Proactive Approach to Retail Security', 'Public Safety'],
  ['Supporting Local Businesses: A Proactive Approach to Retail Security - amendment', 'Public Safety'],
  ['Deferring the Collection of Development Cost Levies (DCLs) and Related Development', 'Finance'],
  ['Local Improvement â€“ Project List of Consideration â€“ Court of Revision 642', 'Finance'],
  ['Approval of Business Improvement Areas (BIAs) Renewals 2026', 'Finance'],
  ['Contract Award for Supply of Contracted Janitorial Services', 'Finance'],
  ['Strengthening Public Trust and Transparency Through Full Disclosure of Total Council Compensation - Amendment to the therefore be it resolved clause', 'Governance'],
  ['Contract Award for Supply of Tree Related Maintenance Services Pre-Qualification', 'Parks'],
  ['Chinatown Strategic Priority Grants', 'Finance'],
  ['Report 2. Chinatown Strategic Priority Grants', 'Finance'],
  ['Report 2. Building By-law Harmonization Opportunities', 'Planning & Development'],
  ['Demolition Permitting Optimization', 'Planning & Development'],
  ['Regulatory Changes Toward 3-3-3-1 Permitting Targets', 'Planning & Development'],
  ['Regulatory Changes to Advance Progress Toward 3-3-3-1 Permitting Targets', 'Planning & Development'],
  ['Regulatory Changes Toward 3-3-3-1 Permitting Targets - Amendment', 'Planning & Development'],
  ['City of Vancouver UNDRIP Task Force Annual Report', 'Governance'],
  ['Endorsement of City Application for UBCM Grant for Next Generation 911', 'Public Safety'],
  ['Below Market Lease and Grant to Pacific Heights Co-op at 1019 Pacific Street', 'Housing'],
  ['Contract Award for Construction Services for Granville Bridge Structural Repairs and Recoating Phase 2', 'Transit'],
  ['Promoting Cultural Inclusion and Economic Vitality: Advancing the Main Street Filipino Cultural Centre and Hotel Project', 'Parks'],
  ['A World Cup for Everyone: Exploring Free Public Viewing Opportunities at BC Place and the PNE Amphitheatre - amendment', 'Parks'],
  ['A World Cup for Everyone: Exploring Free Public Viewing Opportunities at BC Place and the PNE Amphitheatre', 'Parks'],
  ['CD-1 Rezonings: (i) 5392-5472 Manson Street and (ii) 5250-5270 Ash Street and 595 West 37th Avenue', 'Planning & Development'],
  ['Tools and Incentives to Encourage Mass Timber Construction', 'Planning & Development'],
  ['Tools and Incentives to Encourage Mass Timber Construction - Amendment', 'Planning & Development'],
  ['Amendments to the Mayor and Councillors Expenses By-Law', 'Governance'],
  ['Amendments to the Mayor and Councillor Expenses By-law', 'Governance'],
  ['Report 3. Contract Award for Construction Services - City-wide Cut Repair Project', 'Transit'],
  ['Opportunity for a Cultural Precinct in the Heart of Downtown', 'Parks'],
  ['Opportunity for a Cultural Precinct in the Heart of Downtown - Amendment', 'Parks'],
  ['Granville Street Plan - amendment', 'Planning & Development'],
  ['Granville Street Plan - amendment to the amendment', 'Planning & Development'],
  ['Cementing the City of Vancouver\'s Support for Pride Weekend', 'Parks'],
  ['Presentation - VanStat Update on Roads and Sidewalks', 'Transit'],
  ['Presentation - VanStat Update on Roads and Sidewalks - Amendment', 'Transit'],
  ['CD-1 Rezonings: (i) 15-27 West Hastings Street and (ii) 8-36 West Cordova Street', 'Planning & Development'],
  ['CD-1 (893) Text Amendment: 325-343 West 41st Avenue and 5696 Alberta Street - Adopted on Consent', 'Planning & Development'],
  ['CD-1 (454) Text Amendment: 215 West 1st Avenue', 'Planning & Development'],
  ['- Miscellaneous Amendments Concerning Various CD-1 By-laws', 'Planning & Development'],
  ['Closure and Sale of a Portion of Eveleigh Street Adjacent to 1025 Dunsmuir Street', 'Planning & Development'],
  ['Scope Review for Improved Governance', 'Governance'],
  ['Villages Planning Program - Scope of Work', 'Planning & Development'],
  ['2023-2026 Capital Plan Mid-term Update Presentation - amendment 4', 'Finance'],
  ['2023-2026 Capital Plan Mid-term Update Presentation - amendment 3', 'Finance'],
  ['Contract Award for Construction Services - City-wide Cut Repair Project', 'Transit'],
  ['Granville Street Plan - amendment as amended', 'Planning & Development'],
  ['Closure and Conveyance of a Portion of Road within the Granville Loops Lands - Adopted on Consent', 'Planning & Development'],
  ['Modification to a Condition of Enactment for 3077 Maddams Street (formerly 1405 East 15th Avenue & 3047-3071 Maddams Street)', 'Planning & Development'],
  ['Modification to a Condition of Enactment for 3077 Maddams Street', 'Planning & Development'],
  ['Item 3.\tCD-1 (893) Text Amendment: 325-343 West 41st Avenue and 5696 Alberta Street', 'Planning & Development'],
  ['CD-1 (893) Text Amendment: 325-343 West 41st Avenue and 5696 Alberta Street - Adopted on Consent', 'Planning & Development'],
  ['- Miscellaneous Amendments Concerning Various CD-1 By-laws', 'Planning & Development'],
  ['Miscellaneous Amendments â€“ Zoning and Development By-law and Various Other By laws and Land Use Documents', 'Planning & Development'],
  ['Closure and Sale of a Portion of Eveleigh Street Adjacent to 1025 Dunsmuir Street', 'Planning & Development'],
  ['2025 Property Taxation: Pilot Development Potential Relief Program and Targeted Land', 'Finance'],
  ['2025 Community Services & Other Social Grants', 'Finance'],
  ['Vancouver Community Sport Event Grants - Fall 2025 Intake', 'Parks'],
  ['Below Market Lease and Grant to Cedar Mill Co-op at 3385 Marquette Crescent', 'Housing'],
  ['Outstanding Council Motions Update', 'Governance'],
  ['Outstanding Council Motions Update - AMENDMENT', 'Governance'],
  ['Report 1. Housing and Homelessness Services 2026 Grants: Renter Services Grants', 'Housing'],
  ['CD-1 (730) Amendment: 6428-6438 Cambie Street and 480-488 West 48th Avenue (Formerly 478-496 West 48th Avenue) - Adopted on Consent', 'Planning & Development'],
  ['CD-1 (409) Text Amendment: 1109-1139 West Pender Street and 1122-1152 West Hastings Street (Formerly 1128 West Hastings Street)', 'Planning & Development'],
  ['Item 4.\tCD-1 (878) Text Amendment: 357-475 West 41st Avenue', 'Planning & Development'],
  ['CD-1 (878) Text Amendment: 357-475 West 41st Avenue', 'Planning & Development'],
  ['2024 Social Policy Grants Program', 'Finance'],
  ['Contract Award for Construction Services for Upgrading the Thornton Pump Station', 'Climate'],
  ['Update on Accessibility Strategy and Multi-Year Action Plan Implementation - Amendment', 'Governance'],
  ['Update on Accessibility Strategy and Multi-Year Action Plan Implementation - Amended Motion', 'Governance'],
  ['Procedure By-law Update in Response to New Provincial Legislation: Bill 18', 'Governance'],
  ['2023 Community Services and Other Social Grants', 'Finance'],
  ['Closure and Sale of a Portion of Eveleigh Street Adjacent to 1025 Dunsmuir Street', 'Planning & Development'],
  ['CD-1 (511) Text Amendment: 138 East 7th Avenue', 'Planning & Development'],
  ['CD-1 (776) Text Amendment: 118-150 Robson Street (Now 828 Cambie Street)', 'Planning & Development'],
  ['CD-1 (818) Text Amendment: 120-150 West Georgia Street, 720-770 Beatty Street and 701 Expo Boulevard (Formerly 720-770 Beatty Street and 701 Expo Boulevard)', 'Planning & Development'],
  ['CD-1 (409) Text Amendment: 1109-1139 West Pender Street and 1122-1152 West Hastings Street (Formerly 1128 West Hastings Street)', 'Planning & Development'],
  ['Report 6. Business Improvement Areas (BIA) Renewals 2026', 'Finance'],
  ['998 Thurlow Street - Heritage Revitalization Agreement and Heritage Designation', 'Parks'],
  ['Grant to Amicae Co-op for Below Market Lease at 1047 Barclay Street - Adopted on Consent', 'Housing'],
  ['Contract Award for Construction Services   for Granville Bridge South Main Approach and Ramps Rehabilitation - Phase 1', 'Transit'],
  ['Contract Award for Construction Services for Permanent Plazas', 'Parks'],
  ['Urgent Action to Save Car Free Days 2026 - AMENDMENT TO THE AMENDMENT', 'Transit'],
  ['Igniting our Spirits: Bringing Vancouver Together Through Summer Celebration - amendment', 'Parks'],
  ['Resolution - Closure and Sale of a Portion of Eveleigh Street Adjacent to 1025 Dunsmuir Street', 'Planning & Development'],
  ['998 Thurlow Street - Heritage Revitalization Agreement and Heritage Designation', 'Parks'],
  ['2023 OAG Annual Report and 2024 Operational Plan', 'Governance'],
  ['Annual Federation of Canadian Municipalities (FCM), UBCM, LMLGA Membership Fees for 2024 to 2025', 'Finance'],
  ['Potential to Update the Vancouver Building Bylaw to enable Single Egress Stairs Low & Mid-Rise Buildings to Align with Provincial Changes to the B', 'Planning & Development'],
  ['CD-1 (843) Text Amendment: 888 West Broadway (formerly 878-898 West Broadway)', 'Planning & Development'],
  ['CD-1 (519) Text Amendment and Gaming Control Act Approval: 39-65 Smithe Street', 'Planning & Development'],
  ['CD-1 (519) Text Amendment and Gaming Control Act Approval: 39-65 Smithe Street - Amendment', 'Planning & Development'],
  ['Enhanced Tools for Standards of Property Maintenance', 'Planning & Development'],
  ['Unlocking the Creative and Economic Potential of Vancouver\'s Railtown District - Final motion as amended', 'Planning & Development'],
  ['Reopening Clark Drive: Protecting East Vancouverâ€™s Livability and Port Access - Amendment to E and add F', 'Transit'],
  ['Assessing Motor Vehicle Speeding Risk at Vancouver\'s Most Dangerous Intersections', 'Transit'],
  ['Audit of Land Sales and Exchanges - amendment', 'Finance'],
  ['Audit of Land Sales and Exchanges', 'Finance'],
  ['2026 Graffiti Abatement Grants for Business Improvement Areas (BIAs)', 'Finance'],
  ['Building Safer Communities Program - Youth Safety and Violence Prevention Strategy - Amendment C as amended', 'Public Safety'],
  ['Approval of Business Improvement Area (BIA) Renewals and Expansion 2024 - Final vote', 'Finance'],
  ['CD-1 (845) Text Amendment: 728-796 Main Street and 205 Union Street', 'Planning & Development'],
  ['2024 Annual Whistleblower Report', 'Governance'],
  ['Vancouver Community Sport Event Grants â€“ Spring 2025 Intake', 'Parks'],
  ['Single Room Occupancy (SRO) Upgrading Grants - final vote', 'Housing'],
  ['2026 Business Licence, Vehicles for Hire and Animal Control Fees - Amendment', 'Finance'],
  ["Ensuring Councillors Motions Maintain Public Confidence in the Good Rule of the City", 'Governance'],
  ['Building Safer Communities Program - Youth Safety and Violence Prevention Strategy - Amendment E', 'Public Safety'],
  ['Approval of Council Initiatives - Business Improvement Areas; Renewals and Expansion 2024', 'Finance'],
  ['Directions Report: Consideration of Modification to Conditions of Approval 1616-1698 West Georgia Street, CD-1 (812) - Final Vote', 'Planning & Development'],
  ['Residential Laneway Design & Local Improvement Procedure By-Law Updates - Amendment to the Amendment', 'Planning & Development'],
  ['CD-1 Text Amendment: 8 East Broadway (Formerly 2-24 East Broadway and 2520 Ontario Street)', 'Planning & Development'],
  ['Recommitting to $10 a Day Childcare', 'Housing'],
  ['Annual Federation of Canadian Municipalities (FCM), Union of British Columbia Municipalities (UBCM), and Lower Mainland Local Government Association (LMLGA) Membership Fees for 2026 to 2027', 'Finance'],
  ['Approval of Council Initiatives â€“ Business Improvement Area (BIA) Renewals 2023\nNovember 1, 2022', 'Finance'],
  ['2022 Community Services and Other Social Grants', 'Finance'],
  ['Building Safer Communities Program - Youth Safety and Violence Prevention Strategy - final amended A, B, C and E', 'Public Safety'],
  ['Residential Laneway Design & Local Improvement Procedure By-Law Updates - Amended Amendment', 'Planning & Development'],
  ['2024 Graffiti Abatement Grants to Business Improvement Associations (BIAs)', 'Finance'],
  ['2024 Cultural Grants (CASC, Capacity, Cultural Spaces)', 'Parks'],
  ['Unlocking Attainable Home Ownership', 'Housing'],
  ['Declaration of Dangerous Building at 500 Dunsmuir Street, Vancouver - first amendment', 'Public Safety'],
  ["Contract Award for Consulting Services for City of Vancouver False Creek South Landowner's Conceptual Development Plan", 'Planning & Development'],
  ['Change Order to PS20240847-VBPR-RFP - Construction Manager - FIFA World Cup 26 Vancouver Venue Specific Training Site (VSTS)', 'Finance'],
  ["Support for BC Parks Foundation's Learning by Nature Initiative", 'Parks'],
  ['Honouring the Horse: Saving Vancouver\'s Iconic Lunar New Year Community Gala in Chinatown - amendment', 'Parks'],
  ['Approval of Council Initiatives â€“ Business Improvement Area (BIA) Renewals 2023\nNovember 1, 2022', 'Finance'],
  ["Provincial 'Growing Communities Fund': Initial Allocation to City Projects - amendment to the amendment one", 'Finance'],
  ["Allowing Wine-on-Shelf Sales in Vancouver Grocery Stores - Amendments to Zoning and Development By-law", 'Planning & Development'],
  ['Building Safer Communities Program - Youth Safety and Violence Prevention Strategy - final motion D', 'Public Safety'],
  ['Residential Laneway Design & Local Improvement Procedure By-Law Updates - Amended Amendment', 'Planning & Development'],
  ['Regulating Continuous Flame Butane Lighters', 'Public Safety'],
  ['Reimagining and Replacing Kitsilano Outdoor Pool', 'Parks'],
  ['Boundary Road Maintenance Agreement - AMENDMENT', 'Transit'],
  ["Protecting and Enhancing Greenspace for the East End, Chinatown, Hogan's Alley and Strathcona", 'Parks'],
  ['Vancouver Community Sport Events Grants - Fall 2024 Intake', 'Parks'],
  ['Declaration of Dangerous Building at 500 Dunsmuir Street, Vancouver - Second Amendment', 'Public Safety'],
  ['Youth Voices: Amend the Charter for Age Sixteen Starter', 'Governance'],
  ['Nomination Subcommittee Recommendations Transmittal Report', 'Governance'],
  ["Provincial 'Growing Communities Fund': Initial Allocation to City Projects - amendment two", 'Finance'],
  ['Whistleblower Policy Update', 'Governance'],
  ['Creating a Regulatory Framework for Retail Sales of Psilocybin and Entheogens in Vancouver', 'Public Safety'],
  ['Cultural Tourism Events Fund', 'Parks'],
  ['Inappropriate Public Behaviours - Updating the City\'s Violence Prevention Program to Ensure a Respectful and Safe Work Environment for Employees', 'Public Safety'],
  ['Business Improvement Areas (BIA) Renewals and Expansion 2025', 'Finance'],
  ['Update on the Youth Safety and Violence Prevention Strategy 2023-2026 and Building Safer Communities Program Sustainability Plan', 'Public Safety'],
  ['Change Orders for Consulting Services for ServiceNow Resources Augmentation', 'Finance'],
  ['Identifying Progressive Revenues to Protect Public Services', 'Finance'],
  ['No More Developer Handouts: Requiring the Full Replacement of Waived SRA Conversion Fees', 'Housing'],
  ["Ensuring Continuity of the Women's Equity Strategy Following the Closure of the Equity Office", 'Governance'],
  ['2026 Annual Review of Water Rates and Water Works By-law Amendments', 'Finance'],
  ['Demolition Permitting Optimization - Adopted on Consent', 'Planning & Development'],
  ['(519) Text Amendment and Gaming Control Act Approval: 39-65 Smithe Street', 'Planning & Development'],
  ['- Funding Application to the UBCM Community Emergency Preparedness Fund for Emergency Support Services', 'Public Safety'],
  ['CD-1 Text Amendment: Vancouver Community College (1111 East 7th Avenue, 1155 East Broadway and 2350 Glen Drive)', 'Planning & Development'],
  ["Provincial 'Growing Communities Fund': Initial Allocation to City Projects - amendment 3 with D and subection ii", 'Finance'],
  ['CD-1 Text Amendment: 1111 East 7th Avenue, 1155 East Broadway and 2350 Glen Drive', 'Planning & Development'],
  ['Shared Electric Kick Scooter Pilot By-Law Amendments - Adopted on Consent', 'Transit'],
  ["Revisiting and Refreshing Vancouver's Commitment to Safer Slower Streets - Amended Motion", 'Transit'],
  ['Agricultural Land Reserve - Soil Deposit at 2999 West 53rd Avenue', 'Planning & Development'],
  ['Vancouver Civic Theatres Rental Rates 2025-2026', 'Parks'],
  ['CD-1 (25) Amendment: 3215 Macdonald Street', 'Planning & Development'],
  ["Mayor's Budget Task Force Implementation Oversight Committee Recommendations Transmittal Report", 'Governance'],
  ['Expanding the School Travel Planning Program - First Clause of Amendment', 'Transit'],
  ['Removing Obstacles Preventing Sustainable Food Systems in Vancouver', 'Climate'],
  ['Vancouver Community Sport Event Grants â€“ Fall 2023 Intake - Adopted on Consent', 'Parks'],
  ['Vancouver Civic Theatres Rental Rates 2026-2027', 'Parks'],
  ['2026 Annual Review of Sewer Rates â€“ Sewer and Watercourse By-law', 'Finance'],
  ['Vancouver Civic Theatres Activating Spaces Grant 2023', 'Parks'],
]);

const motions = JSON.parse(fs.readFileSync(path, 'utf8'));
const counts = {};
for (const motion of motions) {
  const next = decisions.get(motion.title);
  if (next && next !== motion.topic) {
    const key = `${motion.topic} -> ${next}`;
    counts[key] = (counts[key] || 0) + 1;
    motion.topic = next;
  }
}
fs.writeFileSync(path, `${JSON.stringify(motions, null, 2)}\n`);
console.log(JSON.stringify({ decisions: decisions.size, changes: counts }, null, 2));
